
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import Nav from "./Component/nav";
import { AppWrapper } from "@/Context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${inter.className} remove-scrollbar caret-transparent bg-zinc-900 border-t-2 px-1 border-zinc-900 rounded-lg `}>
        
          <AppWrapper>
          <Nav />
          {children}
        </AppWrapper></body>
    </html>
  );
}
